/*
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence
whose values do not exceed four million,
find the sum of the even-valued terms.
*/

package main

import "fmt"

func fibonacci(count int32) {
	var index int32
	for index = 0; index <= count; index++ {
		fib := (index - 1) + (index - 2)
		if fib < 0 {
			fib = 0
		}
		if fib >= 4000000 {
			fmt.Println("Max index:", index)
			break
		}
		fmt.Print(fib, ",")
	}
}

func main() {
	fibonacci(1000000)
}
